# Generated by Django 5.1.6 on 2025-05-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_product_image'),
        ('site_app', '0002_remove_order_time_ordered_order_stripe_session_id_and_more'),
    ]

    operations = [
    ]
