# Generated by Django 5.1.6 on 2025-05-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
