# Generated by Django 5.1.6 on 2025-05-05 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_ordered',
        ),
    ]
