import pytest

from test_createanaccountlogout import TestCreateanaccountlogout
from test_loginCreateitemlogout import TestLoginCreateitemlogout
from test_loginthroughsellpage import TestLoginthroughsellpage
from test_loginCreateitemlogoutloginasnewaccountstripetest import TestLoginCreateitemlogoutloginasnewaccountstripetest
from test_messagetest import TestMessagetest
from test_notloggedinVieweverypage import TestNotloggedinVieweverypage
from test_logintest import TestLogintest
from test_testunknowncategory import TestTestunknowncategory
from test_loginVieweverypage import TestLoginVieweverypage
from test_changeaddress import TestChangeaddress
from test_changeaddress2 import TestChangeaddress2
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC