# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginthroughsellpage():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginthroughsellpage(self):
    self.driver.get("http://ec2-184-72-72-187.compute-1.amazonaws.com/")
    self.driver.set_window_size(1359, 899)
    self.driver.find_element(By.CSS_SELECTOR, ".links > li:nth-child(2) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(2) button").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("bob")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("password")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(2)").click()
    #self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > a").click()
    el = self.driver.find_element(By.XPATH, "/html/body/div[1]/nav/ul[1]/li[3]/a")
    self.driver.execute_script("arguments[0].click();", el)
    self.driver.close()
  
if __name__ == "__main__":
  test = TestLoginthroughsellpage()
  test.setup_method(None)
  test.test_loginthroughsellpage()
  test.teardown_method(None)