# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestLoginVieweverypage():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginVieweverypage(self):
    self.driver.get("http://ec2-184-72-72-187.compute-1.amazonaws.com/")
    self.driver.set_window_size(1359, 899)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > a").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("Jack")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("jack")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".links > li:nth-child(1) > a").click()
    el = self.driver.find_element(By.XPATH, "/html/body/div[1]/nav/ul[1]/li[2]/a")
    el3 = self.driver.find_element(By.XPATH, "/html/body/div[1]/nav/ul[1]/li[3]/a")
    el1 = self.driver.find_element(By.XPATH, "/html/body/div[1]/nav/ul[1]/li[1]/a")
    self.driver.execute_script("arguments[0].click();", el)
    self.driver.execute_script("arguments[0].click();", el3)
    self.driver.execute_script("arguments[0].click();", el)
    self.driver.execute_script("arguments[0].click();", el1)
    self.driver.execute_script("arguments[0].click();", el3)
    WebDriverWait(self.driver, 3).until(EC.visibility_of_element_located((By.XPATH, "/html/body/div[1]/div[1]/section/form"))).submit()
    self.driver.close()


  