# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNotloggedinVieweverypage():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_notloggedinVieweverypage(self):
    self.driver.get("http://ec2-184-72-72-187.compute-1.amazonaws.com/")
    self.driver.set_window_size(1359, 899)
    self.driver.find_element(By.CSS_SELECTOR, ".active > a").click()
    el = self.driver.find_element(By.XPATH, "/html/body/div[1]/nav/ul[1]/li[2]/a")
    self.driver.execute_script("arguments[0].click();", el)
    el2 = self.driver.find_element(By.XPATH, "/html/body/div[1]/nav/ul[1]/li[1]/a")
    self.driver.execute_script("arguments[0].click();", el2)
    prof = self.driver.find_element(By.XPATH, "/html/body/div[1]/nav/ul[2]/li[1]/a")
    self.driver.execute_script("arguments[0].click();", prof)
    self.driver.close()
