# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChangeaddress2():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_changeaddress2(self):
    self.driver.get("http://ec2-184-72-72-187.compute-1.amazonaws.com/")
    self.driver.set_window_size(1042, 1034)
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("bob")
    self.driver.find_element(By.ID, "password").send_keys("password")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(1)").click()
    self.driver.find_element(By.ID, "id_address_line1").click()
    self.driver.find_element(By.ID, "id_address_line1").send_keys("test omaha")
    self.driver.find_element(By.ID, "id_address_line2").send_keys("test 2")
    self.driver.find_element(By.ID, "id_city").send_keys("Omaha")
    self.driver.find_element(By.ID, "id_state").send_keys("NE")
    self.driver.find_element(By.ID, "id_zip_code").send_keys("994831")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(7) > button").click()
  
