# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreateanaccountlogout():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createanaccountlogout(self):
    self.driver.get("http://ec2-184-72-72-187.compute-1.amazonaws.com")
    self.driver.set_window_size(1220, 895)
    self.driver.find_element(By.CSS_SELECTOR, ".links > li:nth-child(2) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) button").click()
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("test user46")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("test user")
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("test46@mailinator.com")
    self.driver.find_element(By.ID, "id_location").click()
    self.driver.find_element(By.ID, "id_location").send_keys("2222 S 123 st")
    self.driver.find_element(By.ID, "id_phone_number").click()
    self.driver.find_element(By.ID, "id_phone_number").click()
    self.driver.find_element(By.ID, "id_phone_number").click()
    self.driver.find_element(By.ID, "id_phone_number").click()
    self.driver.find_element(By.ID, "id_phone_number").send_keys("4022043645")
    self.driver.find_element(By.ID, "id_address_line1").click()
    self.driver.find_element(By.ID, "id_address_line1").click()
    self.driver.find_element(By.ID, "id_address_line1").send_keys("1231 S 123 St")
    self.driver.find_element(By.ID, "id_address_line2").click()
    self.driver.find_element(By.ID, "id_address_line2").send_keys("1231 S 123 St")
    self.driver.find_element(By.ID, "id_city").click()
    self.driver.find_element(By.ID, "id_city").click()
    self.driver.find_element(By.ID, "id_city").send_keys("Omaha")
    self.driver.find_element(By.ID, "id_state").click()
    self.driver.find_element(By.ID, "id_state").send_keys("Nebraska")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(10) > label").click()
    self.driver.find_element(By.ID, "id_zip_code").click()
    self.driver.find_element(By.ID, "id_zip_code").send_keys("32142")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(2)").click()
  